Refactory - Network Picker Modal + unit test
bobanetwork/gateway pull request #100
Opened 2023-10-18 14:42 UTC by alvaro-ricotta

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Remove Mui
- Type Interface for Modals
- separate Styles and types externally

Adding Unit Test :
- A Mockstate has been created, and it will likely be improved as we add new test cases for different modals. (Global)
- A middleware was added to Redux to intercept changes in the store. (Global)
- Test cases have been loaded to check the state of the element when it is open.
- A test case has been added to check the dispatch of type 'UI/MODAL/CLOSE'.
- Test cases have been loaded to check that the component does not exist when the state is not open.

2023-10-18 14:44 UTC, sk-enya commented
Please make sure to update the description of PR so we can understand what are these changes for?

2023-10-18 14:47 UTC, sk-enya commented on src/containers/modals/networkPicker/index.test.tsx
> +      })}
Do we need this state config object to run the test?

2023-10-18 14:48 UTC, alvaro-ricotta commented on src/containers/modals/networkPicker/index.test.tsx
> +      })}
Yep, cuz this ask for activeNetwork and activeNetworkType also it requesting for NetworkLayer.

2023-10-18 14:48 UTC, sk-enya approved these changes
Looks good! please review add comments.

2023-10-18 14:48 UTC, sk-enya commented on src/containers/modals/networkPicker/index.test.tsx
> +  it('Open NetworkPickerModal', () => {
along with this can you please add the test for close modal as well!

2023-10-18 14:50 UTC, alvaro-ricotta commented on src/containers/modals/networkPicker/index.test.tsx
> +  it('Open NetworkPickerModal', () => {
for sure.

2023-10-18 15:45 UTC, jemeza approved these changes
LGTM

2023-10-19 09:21 UTC, sk-enya commented
@alvaro-ricotta is there any pending on this?

2023-10-19 16:08 UTC, sk-enya commented on package.json
> +    "redux-thunk": "^2.4.2",
Make sure to test whole app to make sure it's not breaking any where else.

2023-10-19 16:13 UTC, sk-enya commented on src/containers/modals/networkPicker/index.test.tsx
> +  it('NetworkPickerModal is Visible', () => {
```suggestion
 test('Should be visible', () => {
```
As described has component name so in each unit test we don't need to add name again.


If it's unit test let's make use of react testing library with `test` and `it` is part of cypress please take note and do needfull.

2023-10-19 16:13 UTC, sk-enya commented on src/containers/modals/networkPicker/index.test.tsx
> +  it('NetworkPickerModal is Close after click on close button', async () => {
as mention above.

2023-10-19 16:13 UTC, sk-enya commented on src/containers/modals/networkPicker/index.test.tsx
> +  it('NetworkPickerModal should not be visible', () => {
as mention above

2023-10-19 16:14 UTC, sk-enya requested changes
Please update the code as per the comments!

2023-10-20 02:24 UTC, jemeza approved these changes
good stuff! I like the test :)

2023-10-20 06:14 UTC, sk-enya commented on src/containers/modals/networkPicker/index.test.tsx
> +  it('Should be visible', () => {
As mention earlier this `it`=> `test` please fix this as we these are the unit test not cypress.

2023-10-20 06:14 UTC, sk-enya commented on src/containers/modals/networkPicker/index.test.tsx
> +  it('Should dispatch close modal action on click close button', async () => {
same as mention above.

2023-10-20 06:15 UTC, sk-enya requested changes
Looks good! please make changes to test as this is the unit test not a cypress integration test.

2023-10-20 12:34 UTC, alvaro-ricotta commented on src/containers/modals/networkPicker/index.test.tsx
> +  it('Should dispatch close modal action on click close button', async () => {
Updated

2023-10-20 12:35 UTC, sk-enya approved these changes

2023-10-20 12:57 UTC, merged