Refactory/wallet selector modal
bobanetwork/gateway pull request #114
Opened 2023-10-24 18:40 UTC by alvaro-ricotta

Describe your changes and implementation choices. More details make PRs easier to review.

Remove Mui
Reuse Modal Interface
separate Styles and types externally
Adding Unit Test :

Test cases have been loaded to check the state of the element when it is open.
A test case has been added to check the dispatch of type 'UI/MODAL/CLOSE'.
Test cases have been loaded to check that the component does not exist when the state is not open.

2023-10-25 04:50 UTC, sk-enya requested changes

2023-10-25 04:50 UTC, sk-enya commented on src/containers/modals/walletSelector/WalletSelectorModal.tsx
> +}
why do we need to declare global? if needed this is not the right place to do better to add in root level `types.d ` file. or please look into the correct place to add.

2023-10-25 04:50 UTC, sk-enya commented on src/containers/modals/walletSelector/index.test.tsx
> +import React from 'react'
Along with common test please add the test cases for the click or hover event if any. 

Like in this case we have `handleSetWallet` or `handleWalletClick` please make sure to add test for those functions as well.

2023-10-25 15:14 UTC, alvaro-ricotta commented on src/containers/modals/walletSelector/WalletSelectorModal.tsx
> +}
I has been added Global interface based on @metamask/Providers

2023-11-02 03:10 UTC, sk-enya commented
@alvaro-ricotta let's get this close, please do the needed changes

2023-11-11 09:02 UTC, sk-enya commented
@alvaro-ricotta this PR is way lot behind the main branch let's recreate this PR once again from fresh instead of spending time unecessorly to resolve  conflict.

2023-11-11 09:02 UTC, closed without merging