Add Arbitrum/Optimism Support
bobanetwork/gateway pull request #127
Opened 2023-10-31 13:39 UTC by wsdt

## Overview

Add Op/Arb support to Gateway.

## Changes

- Op/Arb support
- Add network feature
- Switch network when changing tab or page
- Several flakes fixed, ..

2023-11-01 04:59 UTC, sk-enya requested changes
Changes looks good, added respective comments and test are missing!

2023-11-01 04:59 UTC, sk-enya commented on src/actions/networkAction.js
> +// export function fetchGas() {
Please remove this if it's not getting used!

2023-11-01 04:59 UTC, sk-enya commented on src/components/bridge/NetworkPickerList/index.tsx
> +  const isLightBridge = useSelector(selectBridgeType()) === BRIDGE_TYPE.LIGHT
can we please keep the separate between selector and conditional check.

Better to keep selector here and move `===` condition to line L128

2023-11-01 04:59 UTC, sk-enya commented on src/components/bridge/NetworkPickerList/index.tsx
> +  const isLightBridge = useSelector(selectBridgeType()) === BRIDGE_TYPE.LIGHT
Or can move this into the useEffect to listen for changes on selector.

2023-11-01 04:59 UTC, sk-enya commented on src/containers/Bridging/BridgeTypeSelector/index.tsx
> +    console.log('LLLL', payload !== BRIDGE_TYPE.LIGHT, isOnLimitedNetwork)
Good to remove consoles!

2023-11-01 04:59 UTC, sk-enya commented on src/containers/Bridging/BridgeTypeSelector/index.tsx
> +  console.log('isonlimit', isOnLimitedNetwork, networkType, network)
Remove console.

2023-11-01 04:59 UTC, sk-enya commented on src/containers/history/History.tsx
> +    <HistoryPageContainer>
please do not remove this Id getting used in integration test.

2023-11-01 04:59 UTC, sk-enya commented on src/services/wallet.service.js
>  See the License for the specific language governing permissions and
Didn't understand what is your changes looks like indentation changes only, but this should not happened as we already `pre-commit` hook in place to format change.

can you please run `yarn format:fix` and then commit again?

2023-11-07 03:58 UTC, sk-enya commented
@wsdt looks like there is conflict can you please take look once? and also E2E tests are failing.

2023-11-07 05:23 UTC, sk-enya commented on src/containers/modals/settings/index.tsx
> +        <SettingsItem></SettingsItem>
Looks like unused empty `SettingsItem` use

2023-11-07 07:19 UTC, sk-enya commented
@wsdt I can see there is lot's of changes but here is note:

`We started following the practice to update the unit test cases based on changes or write the unit test if it's not already present for the file we touched or changed.
We are forcing this more on components, services, containers, hooks mainly.`

Please let me know if you need any help from me.

2023-11-07 07:20 UTC, sk-enya commented
In case of conflict please remove the fast bridge tab from typeSelector.

2023-11-10 16:19 UTC, alvaro-ricotta commented on src/components/icons/chain/L2/ArbitrumIcon.js
use `Svg` component instead?

2023-11-10 16:19 UTC, alvaro-ricotta commented on src/components/layout/Footer/SocialLinks/index.tsx
use conditional render instead of ternary? wallet__version && ()

2023-11-10 16:19 UTC, alvaro-ricotta commented on src/containers/Bridging/tests/BridgeTypeSelector.test.tsx
use mock from utils/tests instead of manually introduce the mockstore

2023-11-10 16:19 UTC, alvaro-ricotta commented on src/containers/modals/settings/index.tsx
SettingRow has been deleted for some specific reason?

2023-11-10 17:15 UTC, wsdt commented on src/components/icons/chain/L2/ArbitrumIcon.js
it is a Svg component, just like the other icons or what do you mean? 
Thank you in advance :-)

2023-11-10 17:16 UTC, wsdt commented on src/components/layout/Footer/SocialLinks/index.tsx
changed thx!

2023-11-10 17:17 UTC, wsdt commented on src/containers/modals/settings/index.tsx
merge conflict, fixed thx!

2023-11-13 09:06 UTC, wsdt commented
@sk-enya @alvaro-ricotta please review thx

2023-11-13 15:14 UTC, alvaro-ricotta approved these changes

2023-11-13 15:14 UTC, alvaro-ricotta commented on src/containers/Bridging/tests/BridgeTypeSelector.test.tsx
Please do not use relative urls 
`import { mockedInitialState } from '../../../util/tests'`
instead use:
`import { mockedInitialState } from 'util/tests'`

2023-11-22 15:56 UTC, sk-enya approved these changes
Looks good!

2023-11-22 16:03 UTC, merged