Update hooks to typescript
bobanetwork/gateway pull request #133
Opened 2023-11-03 19:12 UTC by alvaro-ricotta

Moving Hooks to typescript

2023-11-04 03:41 UTC, sk-enya approved these changes
Please test cases along with migration!

make sure we should have good coverage.

2023-11-04 03:42 UTC, sk-enya requested changes
Test missing please add tests!

2023-11-06 12:59 UTC, alvaro-ricotta commented
> Please test cases along with migration!
> 
> make sure we should have good coverage.

I´m not adding test on ts migration , after migrate to tS i´ll implemente test one by one and push it. it´s just for make ts migration thats all.

2023-11-06 21:23 UTC, sk-enya requested changes

2023-11-06 21:23 UTC, sk-enya commented on src/hooks/useDisconnect/index.ts
> +    }
Looks like this lines has not been covered in tests can you please take look once.

![Screenshot 2023-11-07 at 2 51 14 AM](https://github.com/bobanetwork/gateway/assets/86316370/84f0485c-8431-411c-b509-265900c34a3a)

2023-11-06 21:24 UTC, sk-enya commented
Looks like branch is not update and missing test cases for  `useGoogleAnalytics` if you are already working that's great!

2023-11-07 15:40 UTC, sk-enya approved these changes
Change looks good!
try running test with below command so you will get to know how much code coverage we have.
```
yarn test:w src/hooks/useDisconnect/index.test.tsx --coverage --collectCoverageFrom=src/hooks/useDisconnect/index.ts
```

2023-11-07 15:40 UTC, sk-enya commented on src/hooks/useGoogleAnalytics/index.ts
Are you working writing test cases for this hooks as well?

2023-11-07 15:40 UTC, sk-enya commented on src/hooks/useInterval.ts
Are you working writing test cases for this hooks as well?

2023-11-07 16:01 UTC, merged