Streamlining User Flow
bobanetwork/gateway pull request #144
Opened 2023-11-06 21:59 UTC by jemeza

:clipboard:  closes: 

## Overview

Current gateway disconnects from wallet when the user switches networks, this is annoying for the user.

## Tasks

- [ x] No debug console statement added 
- [ x] Should use only typescript.
- [ ] Does have unit test for each touched file with 90% coverage
- [ x] Does have an integration test if any UI changes.

## Changes

Altered how users switch networks.

## Testing

Snapshots for test coverage for changed files.

## UI Snaps

Add screenshots or video if any visuals changes are there so would be helpful for review.

2023-11-07 04:44 UTC, sk-enya requested changes

2023-11-07 04:44 UTC, sk-enya commented on src/actions/setupAction.js
> +
Looks like dead code please do not add any new dead code if it's of not real use.

2023-11-07 04:44 UTC, sk-enya commented on src/actions/setupAction.js
> +
Please remove not needed as far you are using it to dispatch through component.

2023-11-07 04:44 UTC, sk-enya commented on src/hooks/useWalletConnect.ts
We started following the practice to update the unit test cases based on changes or write the unit test if it's not already present for the file we touched or changed.

We are forcing this more on `components`, `services`, `containers`, `hooks` mainly.

2023-11-07 04:44 UTC, sk-enya commented on src/services/wallet.service.test.ts
> +      })
@jemeza looks like you haven't invoke the switchChain at all from test but then how come the value of `userTriggeredSwitchChain` is going to be `true` and dispatch is getting trigger with payload.

2023-11-07 04:44 UTC, sk-enya commented on src/services/wallet.service.ts
> +        }
Can you please reverse the condition so we don't have to think it loud and can grab it easily.

```suggestion
        if (this.userTriggeredSwitchChain) { // just check for true directly.
          store.dispatch({
            type: 'SETUP/USER_TRIGGERED_CHAIN_SWITCH/SET',
            payload: true,
          })
        } else {
          store.dispatch({
            type: 'SETUP/CHAINIDCHANGED/SET',
            payload: Number(chainId),
          })
        }
```

2023-11-07 04:44 UTC, sk-enya commented on src/services/wallet.service.test.ts
> +      })
As initial value of flag is `false`

2023-11-07 04:46 UTC, sk-enya commented
@jemeza changes are great, the user connect flow is quite good and streamlined now. 
Great work 🥇

Let's resolve comments as earliest possible I can't wait to get this merge.

2023-11-07 04:47 UTC, sk-enya commented on src/actions/setupAction.js
> +
resolved.

2023-11-07 07:14 UTC, jemeza commented on src/services/wallet.service.ts
> +    this.userTriggeredSwitchChain = true
@sk-enya I set `this.userTriggeredSwitchChain = true` here. This is the only function used to switch chains in the gateway thus this function will be called if the user attempts to switch chain.

2023-11-07 07:15 UTC, sk-enya commented on src/services/wallet.service.ts
> +    this.userTriggeredSwitchChain = true
Absolutely understandable, but case of test above where I mention the comment didn't added call for this function but your testing on `true` value of var that's what I am confused!

2023-11-07 07:16 UTC, jemeza commented on src/services/wallet.service.test.ts
> +      })
I set `userTriggeredSwitchChain` in the function `async switchChain(chainId: any, chainInfo: any)` that starts on line 179 of `wallet.service.ts`. Please see comment below.

2023-11-07 07:17 UTC, sk-enya commented on src/services/wallet.service.test.ts
> +      })
please check latest comments!

2023-11-07 07:17 UTC, sk-enya commented on src/services/wallet.service.test.ts
> +      })
anyways that's not blocker at all. thanks for effort.

2023-11-07 07:18 UTC, sk-enya commented on src/hooks/useWalletConnect.ts
@jemeza can you please add test cases for useWalletConnect if you don't mind?

2023-11-07 07:24 UTC, jemeza commented on src/services/wallet.service.ts
> +    this.userTriggeredSwitchChain = true
Gotcha, check lines 126, 137, and 153. In these lines `switchChain` is called all with the same chain ID. In this case `this.userTriggeredSwitchChain`  is set to `true` and the callback function does not update the value of `this.userTriggeredSwitchChain` since the chain ID has not changed. 
 

Maybe it's better to add logic in the function `switchChain` that will ignore calls to the function if the chainId is the same as the current chainID?

2023-11-07 07:25 UTC, jemeza commented on src/services/wallet.service.ts
> +    this.userTriggeredSwitchChain = true
We could also leave it at is, please let me know what you prefer.

2023-11-07 07:27 UTC, jemeza commented on src/hooks/useWalletConnect.ts
I can but I know that @alvaro-ricotta was also working on tests for the hooks. Should I wait to see if he's already done it?

2023-11-08 03:35 UTC, sk-enya commented on src/services/wallet.service.ts
> +    this.userTriggeredSwitchChain = true
okay no issues!

2023-11-08 09:40 UTC, sk-enya approved these changes
Looks good!

2023-11-08 09:41 UTC, merged