Feat/e2e bridging test
bobanetwork/gateway pull request #172
Opened 2023-11-13 21:40 UTC by jemeza

:clipboard:  closes: #49 #50 

## Overview

Adds test for bridging on Goerli testnet

## Tasks

- [x] No debug console statement added 
- [x] Should use only typescript.
- [x] Does have unit test for each touched file with 90% coverage
- [x] Does have an integration test if any UI changes.

## Changes

- Created new bridging spec file: `bridging.spec.cy.ts`
- Added test for bridging from L1 to L2
- Added test for bridging from L1 to L2 to a different address
- Made minor refactoring changes necessary for the above to be readable

## Testing

Snapshots for test coverage for changed files.

## UI Snaps

Add screenshots or video if any visuals changes are there so would be helpful for review.

2023-11-17 15:39 UTC, sk-enya requested changes

2023-11-17 15:39 UTC, sk-enya commented on cypress.config.ts
> +    ],
why do need to add paths explicitly?
earlier one is good with `**/*.spec.cy.ts`

2023-11-17 17:18 UTC, jemeza commented on cypress.config.ts
> +    ],
Adding paths explicitly allows for test to be ran in order. We shouldn't test bridging functionality if the connect functionality is not working.

2023-11-21 15:56 UTC, sk-enya approved these changes

2023-11-21 15:56 UTC, sk-enya commented on cypress.config.ts
> +    ],
okay looks good!

2023-11-21 18:13 UTC, merged