Hooks - useWalletConnect - unit tests
bobanetwork/gateway pull request #204
Opened 2023-11-22 13:38 UTC by alvaro-ricotta

## Testing

![image](https://github.com/bobanetwork/gateway/assets/81116391/c6867ec0-130d-494e-87f9-33dbf23731ad)

- Layer L1/L2 should triggerInit if accountEnable is false and baseEnabled is true
- Layer L1/L2 should triggerInit if accountEnable is true and baseEnabled is true but chain has been changed
- triggerInit should Open No Metamask Modal when intialized === nometamask
- triggerInit should Open Wrong Network Modal when intialized === wrongnetwork
- triggerInit should Set account enabled False when intialized === false
- triggerInit should Close wrong network modal , setLayer , setEnabledAccout, setWalletAddress and addTooken when initialized === L1 or L2
- triggerInit should return false when intialized is not defined
- connectBOBARequest should tigger doConnectToLayer(L2), reset chain Connection and open walletSelectorModal when provider is not defined
- connectETHRequest should tigger doConnectToLayer(L1), reset chain Connection and open walletSelectorModal

2023-11-23 19:36 UTC, sk-enya requested changes
Please follow the PR structure for descriptions. you can inject as much details and helpful for reviewer to read it correctly.
![Screenshot 2023-11-24 at 1 06 05 AM](https://github.com/bobanetwork/gateway/assets/86316370/4e772cc0-3afe-4501-a436-9fa179d8a546)

2023-11-23 19:36 UTC, sk-enya commented on src/hooks/useWalletConnect/index.ts
> +      console.log('insideConnectEthRequest')
please remove console.

2023-11-23 19:36 UTC, sk-enya commented on src/hooks/useWalletConnect/index.ts
> +      console.log('inside connect boba request')
remove consoles!

2023-11-23 19:36 UTC, sk-enya commented on src/hooks/useWalletConnect/index.ts
> +      console.log('inside connectRequest')
remove consoles!

2023-11-23 19:36 UTC, sk-enya commented on src/util/tests/index.ts
> +export const DISABLE_WALLETCONNECT: EnvType = 'true'
Do we really need this? as it's seems duplicate declaration with constant.ts. 

Please add comments so we can refer in future to understand correctly about why we have written this again?

2023-11-24 13:54 UTC, alvaro-ricotta reviewed
all task has been resolved

2023-11-24 13:54 UTC, alvaro-ricotta commented on src/util/tests/index.ts
> +export const DISABLE_WALLETCONNECT: EnvType = 'true'
removed

2023-11-27 07:24 UTC, sk-enya approved these changes

2023-11-27 07:39 UTC, merged