Fix/earn listing
bobanetwork/gateway pull request #229
Opened 2023-12-06 20:54 UTC by sk-enya

:clipboard:  closes: 

## Overview

Describe what your Pull Request is about in a few sentences.

## Tasks

- [x] No debug console statement added 
- [x] Should use only typescript.
- [x] Does have unit test for each touched file with 90% coverage
- [x] Does have an integration test if any UI changes.

## Changes

Describe your changes and implementation choices

Cleanup Earn Component

- Prepare new Earnlisting container component
- Prepare new EarnListItem component with functional component for react and batter handling of state.
- ERarn listing of stake and rewards
- Refactored functional logic for unstake / withdrawal
- Unit testing and refactoring.

## Testing

Snapshots for test coverage for changed files.

## UI Snaps

Add screenshots or video if any visuals changes are there so would be helpful for review.

2023-12-07 18:18 UTC, jemeza requested changes
Hey Sahil, it seems that the directories `src/earn/EarnList` and `src/earn/earnList` are copies of each other. Is this correct? If so why?

2023-12-07 18:18 UTC, jemeza commented on src/containers/earn/earnList/earnListItem/index.tsx
what is the difference between this file and `src/containers/earn/EarnList/earnListItem/index.tsx` ? Their names are barely different and the functionality looks the same. Is this a duplicate perhaps?

2023-12-09 05:28 UTC, sk-enya commented on src/containers/earn/earnList/earnListItem/index.tsx
we will cleanup this as I am unable to see on my local once this PR is merged we will remove the folder with Capital Later.

2023-12-11 15:33 UTC, alvaro-ricotta approved these changes

2023-12-13 05:28 UTC, merged