Fixes Issues in the token list of the token picker modal.
bobanetwork/gateway pull request #287
Opened 2024-01-06 00:11 UTC by jemeza

:clipboard:  closes: 

## Overview

When switching from an Ethereum network (Testnet or Mainnet) to a BNB network (Testnet or Mainnet) the `tokenList`, which is the state that is defined and maintained in `reducers/tokenReducer` was not updated properly. Previously, after the user attempted to switch networks, `setupInitState({ l1Token, l1TokenName })`, in `services/app.service.ts`, would be called which would update the `tokenList` mentioned above with the correct native L1 token. However, subsequently, the `tokenList` was reset by a call to `restTokenList` in `src/containers/modals/wrongNetwork/WrongNetworkModal.tsx` and as a result the `tokenList` would incorrectly contain `ETH`. The user would then see `ETH` show up in the token picker even if they were connected to a BNB network. 

## Tasks

- [x] No debug console statement added 
- [x] Should use only typescript.
- [x] Does have unit test for each touched file with 90% coverage
- [x] Does have an integration test if any UI changes.

## Changes

Describe your changes and implementation choices

- Replacing `restTokenList` with `initializeTokenList`. This is triggered when the user changes networks. 
- Changing `setupInitState({ l1Token, l1TokenName })`, in `services/app.service.ts` to dispatch the action that initializes the token list with the native L1 token.

## Testing

n/a

## UI Snaps

2024-01-19 17:19 UTC, sk-enya requested changes

2024-01-19 17:19 UTC, sk-enya commented on src/containers/modals/tokenPicker/TokenPickerModal.tsx
> +    }
Instead of hardcoding can we move this to constant or as it's address let's import it from appservice or networkservice, so it will be easy to understand what does this address mean or which token it is?

2024-01-19 17:19 UTC, sk-enya commented on src/containers/modals/tokenPicker/TokenPickerModal.tsx
> +                      {shouldHaveOptionToAddToken(token) && (
Instead of calling function here let's add condition directly like or make it variable to avoid rerenderings.

2024-01-19 17:19 UTC, sk-enya commented on src/containers/modals/wrongNetwork/WrongNetworkModal.tsx
> -
@jemeza 
Please double check and make sure to cleanup token list after network change or wrong network otherwise user might see the old data on UI and get confused.

2024-01-19 17:19 UTC, sk-enya commented on src/reducers/tokenReducer.ts
> +      state = { [action.payload.currency]: action.payload }
looks like this will be failed as you are not passing anything into the `action.payload` please check once again in the actions above and pass the missing payload.

``` javascript
export const initializeTokenList = () => (dispatch) =>
  dispatch({ type: 'TOKEN/GET/INITIALIZE' })

```

2024-01-19 17:19 UTC, sk-enya commented on src/services/app.service.ts
> +      type: 'TOKEN/GET/INITIALIZE',
Can you please check once looks like you have used same name for `Reset` & `Success`

2024-01-19 17:49 UTC, jemeza commented on src/containers/modals/tokenPicker/TokenPickerModal.tsx
> +    }
Yes sounds good

2024-01-19 17:49 UTC, jemeza commented on src/containers/modals/tokenPicker/TokenPickerModal.tsx
> +                      {shouldHaveOptionToAddToken(token) && (
ok

2024-01-19 17:50 UTC, jemeza commented on src/containers/modals/wrongNetwork/WrongNetworkModal.tsx
> -
The current implementation causes old data on the UI to persist.

2024-01-19 17:57 UTC, jemeza commented on src/reducers/tokenReducer.ts
> +      state = { [action.payload.currency]: action.payload }
Hmm, I can see why this is confusing. The function `initializeTokenList` is never called, I left it there for readability. What really calls `TOKEN/GET/INITIALIZE` is:

`setupInitState({ l1Token, l1TokenName }) {
    store.dispatch({
      type: 'TOKEN/GET/INITIALIZE',
      payload: {
        currency: L1_ETH_Address,
        addressL1: L1_ETH_Address,
        addressL2: L2_SECONDARYFEETOKEN_ADDRESS,
        symbolL1: l1Token,
        symbolL2: l1Token,
        decimals: 18,
        name: l1TokenName,
        redalert: false,
      },
    })
  }`


Which calls with parameters.

2024-01-19 18:23 UTC, jemeza commented on src/services/app.service.ts
> +      type: 'TOKEN/GET/INITIALIZE',
'TOKEN/GET/RESET' is no longer used. Essentially, 'TOKEN/GET/INITIALIZE' is called every time the user connects to a network which effectively resets the token list.

2024-01-19 19:27 UTC, jemeza commented on src/reducers/tokenReducer.ts
> +      state = { [action.payload.currency]: action.payload }
I removed  
```export const initializeTokenList = () => (dispatch) =>
  dispatch({ type: 'TOKEN/GET/INITIALIZE' })
```
to avoid confusion.

2024-01-20 10:06 UTC, sk-enya commented on src/services/app.service.ts
> +      type: 'TOKEN/GET/INITIALIZE',
Awesome, thanks!

2024-01-20 10:08 UTC, sk-enya approved these changes
Looks good!

2024-01-21 19:46 UTC, wsdt approved these changes

2024-01-22 17:31 UTC, merged