Close modal and show the appropriate error to the user on failed tx instead of claim button!
bobanetwork/gateway pull request #408
Opened 2024-03-12 22:26 UTC by sk-enya

:clipboard:  
closes: https://github.com/bobanetwork/gateway/issues/392

## Overview

Close modal and show the appropriate error to the user on failed tx instead of claim button

2024-03-13 11:39 UTC, alvaro-ricotta approved these changes

2024-03-13 12:43 UTC, souradeep-das approved these changes

2024-03-13 14:20 UTC, wsdt commented on src/containers/modals/MultiStepWithdrawalModal/VerticalStepper.tsx
> +        dispatch(openError(`Failed to prove withdrwal!`))
```suggestion
        dispatch(openError(`Failed to prove withdrawal!`))
```

2024-03-13 14:20 UTC, wsdt commented on src/containers/modals/MultiStepWithdrawalModal/VerticalStepper.tsx
> +        dispatch(openError(`Failed to initiate withdrwal!`))
```suggestion
        dispatch(openError(`Failed to initiate withdrawal!`))
```

2024-03-13 14:21 UTC, wsdt commented on src/services/transaction.service.ts
>      return filteredResults.filter((transaction) => transaction?.hash)
Does this remove duplicates? The commented snippet was the fix to Jason's bug.

2024-03-13 14:22 UTC, wsdt requested changes
left comments

2024-03-14 04:23 UTC, sk-enya commented on src/services/transaction.service.ts
>      return filteredResults.filter((transaction) => transaction?.hash)
But the comment to fix the Boyuan's bug? LOL

2024-03-14 05:12 UTC, sk-enya commented on src/services/transaction.service.ts
>      return filteredResults.filter((transaction) => transaction?.hash)
You mean https://github.com/bobanetwork/gateway/issues/382 ?

2024-03-14 05:53 UTC, sk-enya commented on src/services/transaction.service.ts
>      return filteredResults.filter((transaction) => transaction?.hash)
Please review the latest commit added fix for the duplication!

2024-03-14 06:01 UTC, sk-enya commented on src/services/transaction.service.ts
>      return filteredResults.filter((transaction) => transaction?.hash)
Fix has been updated in latest commit!

2024-03-14 10:54 UTC, wsdt approved these changes
awesome looks good now!

2024-03-14 13:41 UTC, merged